global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "Book-My-Movie-App"
    metrics_path: "/BookMyMovie/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]

